---
  
- name: Obtiene Version de Kernel
  hosts: all
  vars:
    filename: /tmp/kernelv.txt
    dst_folder: /tmp/hosts
  tasks:

    - name: Borra archivo Centralizado
      file:
        path: "{{ filename }}"
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Se asegura que el directorio existe
      file:
        path: "{{ dst_folder }}"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Ejecuta Job
      shell: uname -a
      register: kernelv

    - name: Muestra en pantalla
      debug:
        msg: '{{ kernelv.stdout }}'

    - name: Muestra Salida por Host
      copy:
        content: "{{ kernelv.stdout }}"
        dest: "{{ dst_folder }}/{{ ansible_hostname }}.txt"
      delegate_to: localhost

    - name: Muestra Salida por archivo Centralizado
      lineinfile:
        path: "{{ filename }}"
        line: "{{ ansible_hostname }} {{ kernelv.stdout.split(\" \")[2] }}"
        create: true
      delegate_to: localhost

...